// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAscTF4DDDqwEBFFJuHxw3rxzo9jUCxXd8',
    appId: '1:949533101051:web:6c8614e5ecdd59a6a7195e',
    messagingSenderId: '949533101051',
    projectId: 'student-34114',
    authDomain: 'student-34114.firebaseapp.com',
    storageBucket: 'student-34114.appspot.com',
    measurementId: 'G-E4VZGK5129',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH-iJaC3m0h74kGZq67ZywxFGnpjUQ5L4',
    appId: '1:949533101051:android:2c2e351dbbfa27d3a7195e',
    messagingSenderId: '949533101051',
    projectId: 'student-34114',
    storageBucket: 'student-34114.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq7H19ZBE1hu0zSY8MfHRzZmeQPJvCAY0',
    appId: '1:949533101051:ios:abd6d3106a631194a7195e',
    messagingSenderId: '949533101051',
    projectId: 'student-34114',
    storageBucket: 'student-34114.appspot.com',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBq7H19ZBE1hu0zSY8MfHRzZmeQPJvCAY0',
    appId: '1:949533101051:ios:abd6d3106a631194a7195e',
    messagingSenderId: '949533101051',
    projectId: 'student-34114',
    storageBucket: 'student-34114.appspot.com',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAscTF4DDDqwEBFFJuHxw3rxzo9jUCxXd8',
    appId: '1:949533101051:web:4eaed0c9578c87e9a7195e',
    messagingSenderId: '949533101051',
    projectId: 'student-34114',
    authDomain: 'student-34114.firebaseapp.com',
    storageBucket: 'student-34114.appspot.com',
    measurementId: 'G-4R1SZH7EL9',
  );
}
